### ISSUE TITLE
Update to latest SWI release 7.3.12

### ISSUE THREAD

**Issue by rla** [mndrix/docker-swipl#2]
The new 7.3.12 release has many core changes and it would be nice to run stuff with it.

**Comment by mndrix** [comment]
I'm currently on very slow Internet, but plan to do a release on Monday when I have fast Internet again.

I'll post here when it's ready.

**Comment by mndrix** [comment]
Quick update: I won't have fast Internet again until at least tomorrow.  Sorry for the delay.

**Comment by mndrix** [comment]
Since Jan just released 7.3.13, I went ahead and built that and skipped 7.3.12.  Enjoy.

**Comment by rla** [comment]
Thank you!
